

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientBody from "./ClientBody";
import Script from "next/script";

// ⬅️ Add this import
import { LangProvider } from "./providers/lang_provider";

// Use Node.js runtime for better performance with complex pages
export const runtime = "nodejs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Target | Clothe | Admin",
  description: "Generated by Sokchan Dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <Script
          crossOrigin="anonymous"
          src="//unpkg.com/same-runtime/dist/index.global.js"
        />
      </head>

      <body suppressHydrationWarning className="antialiased">

        {/* ⬇️ Wrap everything with LangProvider */}
        <LangProvider>
          <ClientBody>{children}</ClientBody>
        </LangProvider>

      </body>
    </html>
  );
}
